name: dilo
description: Dilo is a new way to share your thoughts and emotions.

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  cherry_toast: ^1.0.8
  cloud_firestore: ^3.4.4
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.6.3
  firebase_core: ^1.20.1
  flutter:
    sdk: flutter
  flutter_chat_bubble: ^2.0.0
  flutter_feather_icons: ^2.0.0+1
  flutter_svg: ^1.1.3
  google_fonts: ^3.0.1
  google_sign_in: ^5.4.1
  ionicons: ^0.2.1
  lottie: ^1.4.1
  provider: ^6.0.3
  timeago: ^3.3.0
  flutter_native_splash: ^2.2.8

flutter_native_splash:
  color: "#FF9908"
  image: assets/logo/dilo_white.png

  android_12:
    color: "#FF9908"
    color_dark: "#A867E9"
    image: assets/logo/dilo_white.png
    image_dark: assets/logo/dilo_white.png

dev_dependencies:
  flutter_lints: ^2.0.0
  change_app_package_name: ^1.1.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0
flutter_icons:
  android: true
  ios: true
  image_path: assets/logo/main.png

flutter:
  uses-material-design: true
  assets:
    - assets/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
